name: buildAndDeployWorker
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: nodejs
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@3.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
